version = 1

[[annotations]]
path = [
    ".gitignore",
    ".pre-commit-config.yaml",
    ".pre-commit-hooks.yaml",
    "README.md",
    "new_version_tag.py",
    "pyproject.toml",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "src/**/*.py",
]
SPDX-License-Identifier = "MIT"
